apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-demo-dep
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: django-demo
    spec:
      containers:
      - name: django-demo-con
        image: $image:$tag
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: django-demo-pro
  name: django-demo-srv
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80 # port that service will serve on
    targetPort: 8000 # port that container published its application
    nodePort: 30800 # set custom port that host publishs in-container application
  selector:
    k8s-app: django-demo

