apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: product_name_production
  name: product_name_service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80 # port that service will serve on
    targetPort: 8000 # port that container published its application
    nodePort: 30800 # set custom port that host publishs in-container application
  selector:
    k8s-app: product_name_app