apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: $image:$tag
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxservice
  name: nginxservice
spec:
  type: NodePort
  ports:
    # The port that this service should serve on.
    - port: 80
      nodePort: 30015
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: nginx
